//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trial
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }
        [Required]
        public string EmpName { get; set; }
        [Required]
        [Range(10000, 10000000, ErrorMessage = "Employee Salary minimum 10000 ")]
        public int Salary { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime DateOfJoining { get; set; }
        [Required]
        public string Designation { get; set; }
        [Required]
        public string City { get; set; }
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
